User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'CollectLSRequestTiming - experiment'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
Python interpreter path: /usr/bin/python3
Error 2021-05-11 11:54:23: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/joey/Downloads/digit-recognition/.vscode/settings.json' (Error: Unable to resolve non-existing file '/home/joey/Downloads/digit-recognition/.vscode/settings.json')
	at _handleError (/snap/code/63/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:156171)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (/home/joey/.vscode/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:9:344717)
	at async p.doesFileNeedToBeFixed (/home/joey/.vscode/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:59:581560)
	at async /home/joey/.vscode/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:59:580687
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/joey/.vscode/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:59:580633)
	at async p.updateTestSettings (/home/joey/.vscode/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:59:580260)] {
  code: 'FileNotFound'
}
Starting Pylance language server.
> conda --version
